### ISSUE TITLE
can-react-component does not work as expected with CanJS 4

### ISSUE THREAD

**Issue by ivospinheiro** [canjs/can-react-component#20]
**Problem:** `can-react-component` does not work with `CanJS 4`

**Issues:**
- Bound properties are not working
- The component view is being rendered twice.

Here is a sample project that demonstrates the issues:
https://github.com/ivospinheiro/can-react-component-issue

**Comment by justinbmeyer** [comment]
Did you list the right url?  

`can-react-component` hasn't been upgraded for 4.0.

**Comment by justinbmeyer** [comment]
Oh, I guess @christopherjbaker did try to upgrade some parts of it.  @christopherjbaker do you know the status of this work?

**Comment by ivospinheiro** [comment]
Sorry @justinbmeyer, i've posted the wrong link.
I've updated the issue with the correct link:
https://github.com/ivospinheiro/can-react-component-issue

**Comment by ivospinheiro** [comment]
@justinbmeyer and @christopherjbaker do you have any idea about when this issue could be solved?
I'm currently working on the upgrade of CanJS version from 3 to 4 and I need this issue to be solved.

**Comment by justinbmeyer** [comment]
I’m out for a training for the next 2 weeks. I could find a time to pair with you and debug it if you have time?

**Comment by ivospinheiro** [comment]
Of course I can pair with you to debug the package.
Please let me know when you have some time.
